spring.application.name=bankai-mcp-server

spring.config.import=optional:configserver:http://localhost:8080

spring.cloud.config.request-connect-timeout=5000
spring.cloud.config.request-read-timeout=5000
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=10
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-interval=2000
spring.cloud.config.retry.multiplier=1.2

spring.profiles.active=mcp

spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.stdio=false
spring.ai.mcp.server.name=bankai-mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.resource-change-notification=true
spring.ai.mcp.server.tool-change-notification=true
spring.ai.mcp.server.prompt-change-notification=true
spring.ai.mcp.server.sse-endpoint=/api/sse
spring.ai.mcp.server.sse-message-endpoint=/api/message
spring.ai.mcp.server.type=sync

spring.ai.mcp.server.capabilities.completion=true
spring.ai.mcp.server.capabilities.prompt=true
spring.ai.mcp.server.capabilities.resource=true
spring.ai.mcp.server.capabilities.tool=true