spring:
  application.name: embedding-service

  ai:
    retry:
      max-attempts: 1      
      on-client-errors: false   
    openai.embedding.enabled: false   
    ollama.embedding.enabled: false     

---
spring:
  config.activate.on-profile: openai
  ai:
    openai:
      api-key: 
      embedding:
        enabled: true
        options:
          model: text-embedding-ada-002

---
spring:
  config.activate.on-profile: ollama
  ai:
    ollama:
      base-url: http://localhost:11434  
      embedding:
        enabled: true
        options:
          model: mxbai-embed-large

---
spring:
  config.activate.on-profile: internal

  ai:
    embedding:
      transformer:
        enabled: true