spring:
  application.name: embedding-service

  ai:
    retry:
      max-attempts: 1      
      on-client-errors: false   
    openai.embedding.enabled: false   
    ollama.embedding.enabled: false     

---
spring:
  config.activate.on-profile: openai
  ai:
    openai:
      api-key: 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
      embedding:
        enabled: true
        options:
          model: text-embedding-ada-002

---
spring:
  config.activate.on-profile: ollama
  ai:
    ollama:
      base-url: http://localhost:11434  
      embedding:
        enabled: true
        options:
          model: mxbai-embed-large

---
spring:
  config.activate.on-profile: internal

  ai:
    embedding:
      transformer:
        enabled: true