spring.application.name=bankai-stock

spring.config.import=optional:configserver:http://localhost:8080

spring.cloud.compatibility-verifier.enabled=false

# Vertex AI / Gemini
#ai.vertex.ai.gemini.chat.options.model=gemini-2.5-flash-preview-05-20
#ai.vertex.ai.gemini.project-id=${GOOGLE_PROJECT_ID}
#ai.vertex.ai.gemini.location=${GOOGLE_ZONE}

# OpenAI
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-3.5-turbo
spring.ai.openai.embedding.model=text-embedding-ada-002

logging.level.org.springframework=ERROR
logging.level.root=ERROR


spring.cloud.config.request-connect-timeout=5000
spring.cloud.config.request-read-timeout=5000
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=10
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-interval=2000
spring.cloud.config.retry.multiplier=1.2

spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.name=bankai-mcp-client
spring.ai.mcp.client.version=1.0.0
spring.ai.mcp.client.initialized=true
spring.ai.mcp.client.request-timeout=20s
spring.ai.mcp.client.type=sync
spring.ai.mcp.client.root-change-notification=true
spring.ai.mcp.client.toolcallback.enabled=true

spring.ai.mcp.client.sse.connections.server.url=http://localhost:8090
spring.ai.mcp.client.sse.connections.server.sse-endpoint=/api/sse

resilience4j.ratelimiter.instances.aiService.limitForPeriod=3
resilience4j.ratelimiter.instances.aiService.limitRefreshPeriod=60s
resilience4j.ratelimiter.instances.aiService.timeoutDuration=0s 

#spring.ai.mcp.client.sse.connections.server2.url=http://localhost:8091
#spring.ai.mcp.client.sse.connections.server2.sse-endpoint=/api/sse

