spring.application.name=bankai-stock

spring.config.import=optional:configserver:http://localhost:8080

spring.cloud.compatibility-verifier.enabled=false

spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-3.5-turbo
spring.ai.openai.embedding.model=text-embedding-ada-002

logging.level.org.springframework=ERROR
logging.level.root=ERROR


spring.cloud.config.request-connect-timeout=5000
spring.cloud.config.request-read-timeout=5000
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.max-attempts=10
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-interval=2000
spring.cloud.config.retry.multiplier=1.2
