spring.application.name=bankai-mcp-client
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-interval=2000
spring.cloud.config.retry.multiplier=1.2

spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.name=bankai-mcp-client
spring.ai.mcp.client.version=1.0.0
spring.ai.mcp.client.initialized=true
spring.ai.mcp.client.request-timeout=20s
spring.ai.mcp.client.type=sync
spring.ai.mcp.client.root-change-notification=true
spring.ai.mcp.client.toolcallback.enabled=true

spring.ai.mcp.client.sse.connections.server.url=http://localhost:8090
spring.ai.mcp.client.sse.connections.server.sse-endpoint=/api/sse

resilience4j.ratelimiter.instances.aiService.limitForPeriod=3
resilience4j.ratelimiter.instances.aiService.limitRefreshPeriod=60s
resilience4j.ratelimiter.instances.aiService.timeoutDuration=0s 