spring.application.name=prompt
spring.ai.openai.api-key=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
spring.ai.openai.model=gpt-4.1

#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.model=mistral:latest

#logging.level.org.springframework.ai=DEBUG
#logging.level.org.zalando.logbook= TRACE
#logbook.format.style=http